### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by rainzee** [richardchien/purepress#12]
安装失败，Python 版本 3.11.9，系统为 Windows 10，在 MacOS 下依旧安装失败，具体报错如下

```
Workspace\Python\pure via 🐍 v3.11.9 (pure)
❯ pip install -i https://mirrors.bfsu.edu.cn/pypi/web/simple --upgrade purepress
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting purepress
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/a4/82/14ab91e117216d4795a8da49a99740ecc6355272a2c665ccd22a5eed5af4/purepress-0.6.1-py3-none-any.whl (9.7 kB)
Collecting Flask<2.0.0,>=1.1.2 (from purepress)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/e8/6d/994208daa354f68fd89a34a8bafbeaab26fda84e7af1e35bdaed02b667e6/Flask-1.1.4-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 1.8 MB/s eta 0:00:00
Collecting Markdown<3.3.0,>=3.2.2 (from purepress)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/a4/63/eaec2bd025ab48c754b55e8819af0f6a69e2b1e187611dd40cbbe101ee7f/Markdown-3.2.2-py3-none-any.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.0/89.0 kB 2.5 MB/s eta 0:00:00
Collecting PyYAML<5.5.0,>=5.4.1 (from purepress)
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 10.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\rainzee\Dev\Workspace\Python\pure\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\rainzee\Dev\Workspace\Python\pure\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rainzee\Dev\Workspace\Python\pure\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\rainzee\AppData\Local\Temp\pip-build-env-xze7uhzb\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by rainzee** [comment]
使用 uv 安装报错如下

```
Workspace\Python\pure via 🐍 v3.11.9 (pure) took 8s
❯ uv pip install -i https://mirrors.bfsu.edu.cn/pypi/web/simple --upgrade purepress
Resolved 18 packages in 14ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pyyaml==5.4.1
  Caused by: Failed to build: `pyyaml==5.4.1`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit code: 1
--- stdout:
running egg_info
writing lib3\PyYAML.egg-info\PKG-INFO
writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
writing top-level names to lib3\PyYAML.egg-info\top_level.txt
--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 271, in <module>
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\dist.py", line 968, in run_command
    super().run_command(command)
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
    self.find_sources()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
    mm.run()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
    self.add_defaults()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
    sdist.add_defaults(self)
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
    super().add_defaults()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults
    self._add_defaults_ext()
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
    self.filelist.extend(build_ext.get_source_files())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 201, in get_source_files
  File "C:\Users\rainzee\AppData\Local\uv\cache\.tmpY9LHcp\.venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: cython_sources
---
```

**Comment by brightmann** [comment]
@rainzee ,要去virtualenv里面安装，基本上就没什么问题

**Comment by rainzee** [comment]
> @rainzee ,要去virtualenv里面安装，基本上就没什么问题

额，跟这个有什么关系吗，另外我就是在 venv 中啊

**Comment by stdrc** [comment]
试试最新的 `0.10.0` 版本呢，我刚发布了，版本支持到了 `>=3.12,<3.14`

**Comment by rainzee** [comment]
确实没问题了
